hot_words = ["Ploof", "Snurple", "Snirtle", "Flummock", "Sanger", "Glonk",
             "Vindaloo", "Breeble", "Whismy", "Partele", "Twibble", "Maliby", "Netbeau", "Fremulon", "Dimplet",
             "Sadnfroy", "Fickan", "Escalery", "Saudid", "Merakish"
             ]
hot_phrases = [("Each", "each"),
               ("Brighter", "bitter"),
               ("Mob", "mab"),
               ("Pony", "screw"),
               ("Glimpea", "Shell"),
               ("Both", "Every"),
               ("Running", "Breeze"),
               ("Lamppost", "Shade"),
               ("Stairs", "Overcasting"),
               ("Reflection", "Smooth"),
               ("Tower", "Boat"),
               ("Supra", "Inferior"),
               ("Case", "Ears"),
               ("Steele", "Bubble"),
               ("Neon", "Graffiti"),
               ("Warehouse", "Boulevard"),
               ("Asphalt", "Metro"),
               ("Sediment", "Plateau"),
               ("Mesa", "Quarts"),
               ("Edition", "Circulation")
               ]
